apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-list-watch-pod
  namespace: prometheus
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-list-watch-pod-binding
  namespace: prometheus
subjects:
- kind: ServiceAccount
  name: get-list-watch-pod
  namespace: prometheus
roleRef:
    kind: Role
    name: get-list-watch-pod
    apiGroup: rbac.authorization.k8s.io