apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: checkoutservice-prod
  template:
    spec:
      containers:
      - name: server
        resources:
          requests:
            cpu: 120m
            memory: 128Mi
          limits:
            cpu: 220m
            memory: 256Mi