apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: payment
    labels:
        app: payment
spec:
    replicas: 3
    selector:
        matchLabels:
            tier: payment
    template:
        metadata:
            labels:
                app: payment
                tier: payment
        spec:
            containers:
            - name: server
              image: kystkysto/paymentservice:v0.0.1