apiVersion: apps/v1
kind: Deployment
metadata:
    name: paymentservice
    labels:
        app: paymentservice
spec:
    replicas: 3
    selector:
        matchLabels:
            tier: paymentservice
    template:
        metadata:
            labels:
                app: paymentservice
                tier: paymentservice
        spec:
            containers:
            - name: server
              image: kystkysto/paymentservice:v0.0.2